(module
 call-with-query
 (call-with-dynamic-fastcgi-query
  make-query
  ;; query->alist
  query-client
  query-client-any
  query-client-all
  query-server
  query-server-any
  query-server-all
  query-any
  query-all
  display-eol
  display-header
  content-types
  default-content-type
  display-content-type
  default-xml-prolog
  display-xml-prolog
  doctypes
  default-doctype
  display-doctype
  content-type-&cs.
  default-content-type-&c.
  display-content-type-&c.
  status-continue
  status-switching-protocols
  status-ok
  status-created
  status-accepted
  status-non-authoritative-information
  status-no-content
  status-reset-content
  status-partial-content
  status-multiple-choices
  status-moved-permanently
  status-found
  status-see-other
  status-not-modified
  status-use-proxy
  status-unused
  status-temporary-redirect
  status-bad-request
  status-unauthorized
  status-payment-required
  status-forbidden
  status-not-found
  status-method-not-allowed
  status-not-acceptable
  status-proxy-authentication-required
  status-request-timeout
  status-conflict
  status-gone
  status-length-required
  status-precondition-failed
  status-request-entity-too-large
  status-request-uri-too-long
  status-unsupported-media-type
  status-requested-range-not-satisfiable
  status-expectation-failed
  status-internal-server-error
  status-not-implemented
  status-bad-gateway
  status-service-unavailable
  status-gateway-timeout
  status-http-version-not-supported
  default-status
  display-status
  statuses
  display-status-&c.)

 (import scheme chicken posix)

 (use alist-lib
      debug
      define-record-and-printer
      defstruct
      fastcgi
      format
      irregex
      matchable
      ports
      srfi-1
      srfi-13
      srfi-14
      uri-common)

 (include "call-with-query-core.scm"))
